name: new-year
version: '1.0-SNAPSHOT'
main: kr.isamin.newYear.NewYear
api-version: '1.21'

commands:
  nickname:
    description: 닉네임 관리 명령어
    usage: |
      /<command> reload - 닉네임 데이터 리로드
      /<command> set <플레이어> <닉네임> - 닉네임 설정
      /<command> get <플레이어> - 닉네임 확인
      /<command> reset <플레이어> - 닉네임 초기화
    aliases: [nick]
    permission: new-year.nickname.admin
  realtime:
    description: 현실시간 연동 명령어
    usage: |
      /<command> status - 현재 상태 표시
      /<command> enable - 현실시간 연동 활성화
      /<command> disable - 현실시간 연동 비활성화
    aliases: [rt]
    permission: new-year.realtime.admin

permissions:
  new-year:
    nickname:
      admin:
        description: 닉네임 관리 권한
        default: op
    realtime:
      admin:
        description: 현실시간 관리 권한
        default: op